version: '3.8'
services:

  mysql:
    image: mysql:8.0
    environment:
        MYSQL_ROOT_PASSWORD: Cjql195jsov
        MYSQL_DATABASE: chain_optimizer_schema
    ports:
        - "3306:3306"
    volumes:
        - ./mysql:/var/lib/mysql
        - ./database/schema:/docker-entrypoint-initdb.d

  chainoptimizer:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  mysql-data:
